services:
  - type: web
    name: restaurant-booking
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/tables
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_PORT
        value: 3000
    disk:
      name: data
      mountPath: /app/backend/src/data
      sizeGB: 1
